
# Module manifest for module 'FilesToFolders'
# Generated by: ehmiiz
# Generated on: 9/1/2023

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = '.\obj\Debug\netstandard2.0\FilesToFolders.dll'
    ModuleVersion     = '1.0.0'
    GUID              = '1b434fd6-6a23-4f9f-bc47-2f40a6f2e403'
    Author            = 'ehmiiz'
    CompanyName       = 'ehmiiz.se'
    Copyright         = 'N/A'
    Description       = 'Creates folders based on date, moves files there.'
    PowerShellVersion = '3.0'
    FunctionsToExport = '*'
    CmdletsToExport   = 'Move-FileToFolder'
    VariablesToExport = '*'
    AliasesToExport   = '*'

    PrivateData       = @{

        PSData = @{
            Tags       = 'files', 'folders', 'structure'
            ProjectUri = 'https://github.com/ehmiiz/FilesToFolders'
            # IconUri = ''
        }

    }
}